- lib/torii/providers/oauth2-code.js
- test/tests/integration/providers/facebook-oauth2-test.js
- test/tests/integration/providers/github-oauth2-test.js
- test/tests/integration/providers/google-oauth2-test.js
- test/tests/integration/providers/linked-in-oauth2-test.js
- test/tests/unit/providers/oauth2-code-test.js
When using openid connect the responsecode is not in `code` but in `id_token`. Which is the same as the `responseType` property. This changes it so it uses the `responseType` value as key for getting a token or code from the `authData`.
Will update the azuread PR after this is pulled in.
> use responsetype key for authdata

- lib/torii/providers/facebook-connect.js
The FB JS SDK executes the function assigned to window.fbAsyncInit like this:
if (window.fbAsyncInit && !window.fbAsyncInit.hasRun) {
window.fbAsyncInit.hasRun = true;
h.unguard(window.fbAsyncInit)();
}
Torii overrides `window.fbAsyncInit` and stashes anything already assigned. But the FB SDK will only ever execute the Torii-overridden version. This commit ensures the originally assigned function is called, and the hasRun flag is set, as it is in the SDK.
> Ensure that Facebook Connect triggers fbAsyncInit

- package.json
The `ember-addon.main` path is still needed until https://github.com/ember-cli/ember-cli/pull/3545 is landed in a released version.
This fixes https://github.com/Vestorly/torii/issues/147.
> Fix incorrect `main` entry point script.

- lib/torii/services/popup.js
- test/tests/unit/redirect-handler-test.js
IE8/9 does not like dashes or spaces in the window name. It causes it to throw an Invalid argument error.
This can be reproduced by running the following in an IE8/9 console. `window.open("http://google.com", "with-a-dash")` fails and `window.open("http://google.com", "with_no_dash")` works as expected.
> Fix popup service for IE8/9.

- ember-addon/index.js
Reverts https://github.com/Vestorly/torii/pull/162, and removes usage of `this.app`.
`addon.app` is actually set in the Broccoli setup for top-level included addons ([see here](https://github.com/ember-cli/ember-cli/blob/da0f380f6b4149c98148a26e8948eb84aa98bdd0/lib/broccoli/ember-app.js#L272)).
---
`app` is not passed into the Addon `init` method.  It gets the `parent` passed in, which is a `project` instance when the addon is included as a top level dependency, or an `addon` instance if it is a nested addon.
* Instantiation called [here](https://github.com/ember-cli/ember-cli/blob/eb7fa3725e0e6b2b7a968e6f41c043496907e9c1/lib/models/addons-factory.js#L48) from within the `addonsFactory` helper object.
* `AddonDiscovery` is setup [here](https://github.com/ember-cli/ember-cli/blob/da0f380f6b …
> Avoid using `app` in the Ember Addon.

- lib/torii/lib/query-string.js
- lib/torii/providers/facebook-oauth2.js
- lib/torii/providers/oauth2-bearer.js
- lib/torii/providers/oauth2-code.js
When throwing strings, no stack trace is available (making it much
harder to track down these errors from within nested promises).
> Do not throw strings.

- lib/torii/providers/azure-ad-oauth2.js
- lib/torii/providers/base.js
- lib/torii/providers/facebook-connect.js
- lib/torii/providers/oauth2-code.js
- lib/torii/services/popup.js
- lib/torii/session.js
- test/index.html
* Change usage of `.property()` to `Ember.computed`.
* Change usage of `.on()` to `Ember.on`.
* Update test harness to disable prototype extensions.
> Do not rely on prototype extensions.

- lib/torii/bootstrap/torii.js
- lib/torii/providers/google-oauth2-bearer.js
- test/tests/integration/providers/google-oauth2-bearer-test.js
- test/tests/unit/providers/google-oauth2-bearer-test.js
This PR adds the google-oauth2-bearer provider, which allows Torii users to utilize the client-side OAuth flow outlined here: https://developers.google.com/accounts/docs/OAuth2UserAgent
I originally worked with @rwjblue to get this working in a dummy application before extracting it into a PR. There is quite a bit of duplication between the `google-oauth2-bearer` and `google-oauth2` providers and we discussed creating a mixin to remove the duplication but weren't sure what the desired approach would be. 
The primary difference with the client-side flow above and the server-side flow (https://developers.google.com/accounts/docs/OAuth2WebServer) is the client-side flow immediately grants the consuming application an `access_token` rather than granting an `authorization_code` which is then …
> Add google-oauth2-bearer provider

- lib/torii/providers/facebook-connect.js
Bumped to v2.2. 
I added ability to configure SDK externally with next optional params: version (default to v2.2), xfbml, channelUrl, locale (default to 'en_US')
I added expiresIn to a normalized response.
> Facebook-connect provider SDK version bump, configuration options and token expiration

- lib/torii/services/popup.js
Instead of immediately failing when window is closed; wait for a few seconds to receive the message from postMessage; fixes #111.
I found this necessary at least on Chrome Canary and using the twitter provider.
> wait a bit to receive postMessage in parent window. 

- lib/torii/providers/google-oauth2.js
- test/tests/unit/providers/google-oauth2-test.js
Docs: https://developers.google.com/identity/protocols/OAuth2WebServer#formingtheurl
Fixes https://github.com/Vestorly/torii/issues/139
> Allow to set `approval_prompt` for google-oauth2

- lib/torii/providers/stripe-connect.js
- test/tests/integration/providers/stripe-connect-test.js
This allows `scope` and `stripe_landing` (https://stripe.com/docs/connect/reference) to be set in the stripe-connect's config.
> Allow to set `scope` and `stripe_landing` for stripe-connect

- README.md
- lib/torii/initializers/initialize-torii.js
- lib/torii/instance-initializers/walk-providers.js
- lib/torii/lib/load-instance-initializer.js
- lib/torii/load-initializers.js
This fixes #190 
The main reason is that in modern versions of ember-data the store is registered using instance initializers, and since some providers are trying to inject the store, which is not defined at this point, then boom :boom:  with a quite cryptic error message.
This code will only work in versions of ember with instance initializers (1.12+). I'm not sure if bumping the version number to 0.4 and having support only 1.12, 1.13 and 2.0 is enough or we need to do something cleverer for backwards compatibility.
> Walk providers in a instance-initializer (instead of a regular initializer)

- lib/torii/providers/stripe-connect.js
- test/tests/integration/providers/stripe-connect-test.js
This pull request allows the developer to configure the always_prompt option for stripe connect.
> Added always_prompt option for stripe connect

- README.md
- lib/torii/bootstrap/torii.js
- lib/torii/providers/edmodo-connect.js
- test/tests/integration/providers/edmodo-connect-test.js
- test/tests/unit/providers/edmodo-connect-test.js
This PR adds a provider for Edmodo Connect (see https://developers.edmodo.com/edmodo-connect/). It's very simple as it just re-uses the logic from the `OAuth2Bearer` provider.
> Add a provider for Edmodo Connect

- lib/torii/initializers/initialize-torii-callback.js
- lib/torii/lib/popup-id-serializer.js
- lib/torii/lib/uuid-generator.js
- lib/torii/redirect-handler.js
- lib/torii/services/popup.js
- test/tests/unit/lib/popup-id-serializer-test.js
- test/tests/unit/lib/uuid-generator-test.js
- test/tests/unit/redirect-handler-test.js
- test/tests/unit/services/popup-test.js
This should fix #193. Any feedback and suggestions are welcome.
window.opener was being cleared after visiting a different host in Chrome 43 and Firefox 38. This change uses local storage events + unique popup ids to communicate between windows. Here’s an overview of how it works.
1. When popup.open is called, it generates a new torii popup id (uuid) and sets it as the popup window's name.
2. When RedirectHandler#handle is called in a window that has a valid torii popup id as its name, it stores the popup id and the current url of the popup window in local storage
3. When the new key/value is set in local storage, the popup service is notified via the browser's storage event. If event.key contains the popup id we’re looking for, it extracts the auth code from the url, resolves the …
> Changed inter-window communication to use localStorage events

- lib/torii/redirect-handler.js
- lib/torii/services/popup.js
- test/tests/unit/redirect-handler-test.js
- test/tests/unit/services/popup-test.js
window.name was used to decide what item key would be used for a popup's message to the parent. This is nor reliable, as some browsers leak the fact that Facebook (and other popups) may set a window name that destroys the one set by Torii.
Instead, this patch uses a global key set by torii, identifying a "current channel" that expects to receive the message. This is not perfect, as a window opening a torii request after an different window
may receive the completed auth from the window of the first request. However in a practical sense it means the last window starting auth will receive the messages from auth popups, and old windows that may have started auth will receive none.
See https://github.com/Vestorly/torii/pull/195#issuecomment-119669300
> Remove use of window.name as a channel for localStorage messages

- lib/torii/providers/facebook-connect.js
- test/helpers/build-fb-mock.js
- test/tests/integration/providers/facebook-connect-test.js
Adds a configuration option to facebook-connect provider to return the granted scopes back with the response data. This is useful when trying to determine if a user omitted any required scopes during the sign in process.
Defaults to off and is only added to the normalized response when configured.
> facebook-connect - Add support for return scopes

- lib/torii/lib/random-url-safe.js
- lib/torii/providers/azure-ad-oauth2.js
- lib/torii/providers/facebook-oauth2.js
- lib/torii/providers/github-oauth2.js
- lib/torii/providers/google-oauth2-bearer.js
- lib/torii/providers/google-oauth2.js
- lib/torii/providers/linked-in-oauth2.js
- lib/torii/providers/oauth2-code.js
- lib/torii/providers/stripe-connect.js
- test/helpers/mock-popup.js
- test/tests/integration/providers/azure-ad-oauth2-test.js
- test/tests/integration/providers/facebook-oauth2-test.js
- test/tests/integration/providers/github-oauth2-test.js
- test/tests/integration/providers/google-oauth2-test.js
- test/tests/integration/providers/linked-in-oauth2-test.js
- test/tests/integration/providers/stripe-connect-test.js
- test/tests/unit/providers/azure-ad-oauth2-test.js
- test/tests/unit/providers/edmodo-connect-test.js
- test/tests/unit/providers/google-oauth2-bearer-test.js
- test/tests/unit/providers/oauth2-bearer-test.js
- test/tests/unit/providers/oauth2-code-test.js
- test/tests/unit/providers/stripe-connect-test.js
The OAuth2 code provider (and all subclasses) now default to a generated random "state" URL parameter. This is transmitted to the server, and the provider validates that the same state parameter is received in the response.
This protects against Cross-Site Request Forgery. For more details on this part of the OAuth2 spec, see here RFC 6749 section 10.12:
http://tools.ietf.org/html/rfc6749#section-10.12
The OAuth2 code provider has a default value for `state` which generates and caches a random URL-safe string. This can be overridden by the configuration if the application requires it.
There's also a new mock popup test helper, which defaults to returning the `state` parameter from the request as part of the resolved `authData`. All relevant integration tests have been updated to use this …
> Add CSRF protection for OAuth2 providers via state parameter

- lib/torii/providers/oauth2-bearer.js
- lib/torii/providers/oauth2-code.js
- test/tests/unit/providers/oauth2-bearer-test.js
- test/tests/unit/providers/oauth2-code-test.js
When response params were missing in OAuth2 provider subclasses, the error thrown would list all the required params, instead of only those which are missing.
Fixes #175
> Fix error message on missing response params

- lib/torii/bootstrap/session.js
- lib/torii/bootstrap/torii.js
- lib/torii/initializers/initialize-torii-session.js
- lib/torii/initializers/initialize-torii.js
- lib/torii/services/torii-session.js
- lib/torii/services/torii.js
- test-support/helpers/torii.js
- test/tests/acceptance/ember-init-test.js
- test/tests/acceptance/session-test.js
- test/tests/acceptance/torii-helper-test.js
- test/tests/integration/providers/azure-ad-oauth2-test.js
- test/tests/integration/providers/edmodo-connect-test.js
- test/tests/integration/providers/facebook-connect-test.js
- test/tests/integration/providers/facebook-oauth2-test.js
- test/tests/integration/providers/github-oauth2-test.js
- test/tests/integration/providers/google-oauth2-bearer-test.js
- test/tests/integration/providers/google-oauth2-test.js
- test/tests/integration/providers/linked-in-oauth2-test.js
- test/tests/integration/providers/oauth1-test.js
- test/tests/integration/providers/stripe-connect-test.js
- test/tests/integration/session-test.js
- test/tests/integration/torii-test.js
- test/tests/unit/torii-test.js
Still needs:
Opening this PR for discussion. This PR aims to bring the various Torii singletons inline with Ember Services by using the `Ember.Service` class and registering the singletons using the standard `service:*` naming scheme.
The biggest drawback to this change is breaking changes to anyone currently using the Torii singletons directly (i.e. through `container.lookup`). However, this functionality has been deprecated and the `inject` pattern has been introduced to fill that gap.
Alternatively, we could register the service under both names and maintain backwards compatibility (if this is possible).
> Updates Torii singletons to services

- lib/torii/providers/facebook-connect.js
- test/helpers/build-fb-mock.js
- test/tests/integration/providers/facebook-connect-test.js
Adds the ability to set the `auth_type` when connecting to Facebook. Currently
Facebook only supports `rerequest` which allows for requesting declined 
permissions.
This is not suitable for global configuration because you may not always
want to rerequest permissions but do it based on other conditions. As
such its passed through to the open function in options. It defaults
to not being set (aka the standard facebook-connect auth_type).
> facebook-connect - Add support for auth_type

- README.md
- bower.json
- ember-addon/index.js
- lib/torii/bootstrap/routing.js
- lib/torii/instance-initializers/setup-routes.js
- lib/torii/load-initializers.js
- lib/torii/router-dsl-ext.js
- lib/torii/routing/application-route-mixin.js
- lib/torii/routing/authenticated-route-mixin.js
- lib/torii/services/torii-session.js
- package.json
- test/helpers/initialize-torii.js
- test/helpers/start-app.js
- test/tests/acceptance/routing-test.js
- test/tests/unit/routing/application-route-mixin-test.js
- test/tests/unit/routing/authenticated-route-mixin-test.js
This PR is a follow up to a conversation that @mixonic and I had via Slack about eliminating the need for adding a route mixin to make routes ensure they have authentication. Please, consider this a rough draft. 
This PR provides function called `authenticatedRoute` that can be used in Router map to mark specific routes as requiring authentication. Here is an example:
```js
import Ember from 'ember';
import config from './config/environment';
var Router = Ember.Router.extend({
location: config.locationType
});
export default Router.map(function() {
this.authenticatedRoute('add');
});
```
When at least one `authenticatedRoute` route is present, the app will automatically attempt to `checkLogin` which will call `session.fetch`. To reduce boilerplate, I added a `sessionProvider` property to …
> authenticatedRoute Router DSL

- README.md
- test-support/helpers/torii.js
- test/tests/acceptance/torii-helper-test.js
Torii is agnostic about `currentUser` or any other property being available on the session. Instead, a generic payload can be provided when stubbing session state for acceptance tests.
> stubValidSession accepts session, not currentUser

- lib/torii/bootstrap/routing.js
- lib/torii/lib/container-utils.js
- test/tests/acceptance/routing-test.js
Routing options should not require that the factory actually be present in the container when bootstrapping.
> Allow unregistered factorys to require authentication

- lib/torii/bootstrap/routing.js
By default Ember uses `route:basic` if a route for the specific routename is not found. This emulates that behavior...
> Honor `route:basic` convention for generated routes.

- lib/torii/bootstrap/routing.js
- lib/torii/configuration.js
- lib/torii/instance-initializers/setup-routes.js
- lib/torii/lib/container-utils.js
- lib/torii/lib/parse-query-string.js
- lib/torii/lib/query-string.js
- lib/torii/providers/azure-ad-oauth2.js
- lib/torii/providers/oauth2-code.js
- lib/torii/redirect-handler.js
- lib/torii/services/popup.js
- test/helpers/mock-popup.js
- test/tests/acceptance/ember-init-test.js
- test/tests/acceptance/routing-test.js
- test/tests/unit/adapters/dummy-test.js
- test/tests/unit/configuration-test.js
- test/tests/unit/lib/parse-query-string-test.js
- test/tests/unit/lib/query-string-test.js
- test/tests/unit/providers/azure-ad-oauth2-test.js
- test/tests/unit/providers/dummy-failure-test.js
- test/tests/unit/providers/dummy-success-test.js
- test/tests/unit/providers/edmodo-connect-test.js
- test/tests/unit/providers/google-oauth2-bearer-test.js
- test/tests/unit/providers/google-oauth2-test.js
- test/tests/unit/providers/oauth1-test.js
- test/tests/unit/providers/oauth2-bearer-test.js
- test/tests/unit/providers/oauth2-code-test.js
- test/tests/unit/providers/stripe-connect-test.js
- test/tests/unit/redirect-handler-test.js
- test/tests/unit/services/popup-test.js
Compat with Ember 2.1 primarily calls for:
* Use only the public object invocation syntax of `.create`, not `new`. `new` is private and changes in 2.1.
* Expect `applicationInstance` object instead of containers
* Add hack to work around https://github.com/emberjs/ember.js/pull/12359
> Ember 2.1 compat

- lib/torii/router-dsl-ext.js
The incorrect `_super` call here breaks loading substate code that depends on the `moduleBasedResolver` flag: http://git.io/vnEeC
> Pass _initRouterJs arguments to _super.

- lib/torii/routing/authenticated-route-mixin.js
- test/tests/acceptance/routing-test.js
The `session.attemptedTransition` property is currently set by the authenticated route mixin in its
`authenticate` method when `isAuthenticated === undefined`. `isAuthenticated` will only be `undefined` before the first attempt to `fetch` the session by the adapter. After that initial attempt, `isAuthenticated` will either be boolean `false` or `true`.
This changes the setting of `attemptedTransition` to happen regardless
of whether we have previously attempted to fetch authentication or not,
ensuring that upstream routes will be able to `attemptedTransition.retry()` to return to the route the user had been attempting to visit while unauthenticated.
> Ensure that `session.attemptedTransition` is set

- package.json
Add a demoUrl for emberobserver. See https://twitter.com/EmberObserver/status/605909565264109569 for reference.
> add demoUrl

- README.md
- ember-addon/index.js
- lib/torii/app-components/torii-iframe-placeholder.js
- lib/torii/bootstrap/torii.js
- lib/torii/components/torii-iframe-placeholder.js
- lib/torii/instance-initializers/walk-providers.js
- lib/torii/lib/container-utils.js
- lib/torii/mixins/ui-service-mixin.js
- lib/torii/providers/base.js
- lib/torii/providers/oauth1.js
- lib/torii/providers/oauth2-bearer.js
- lib/torii/providers/oauth2-code.js
- lib/torii/redirect-handler.js
- lib/torii/services/iframe.js
- lib/torii/services/popup.js
- test/tests/unit/bootstrap/torii-test.js
- test/tests/unit/redirect-handler-test.js
- test/tests/unit/services/iframe-test.js
- test/tests/unit/services/popup-test.js
This is a freshly rebased branch of https://github.com/Vestorly/torii/pull/206
The basic overview, which is described in an update to the README is:
You can configure torii to use an in-page iframe instead of a separate
popup window for authentication. This can be done on either a global or
a per-provider basis.
To change this globally set the `remoteServiceName` variable in the main
torii config to be `'iframe'`.
```JavaScript
/* jshint node: true */
// config/environment.js
module.exports = function(environment) {
var ENV = {
/* ... */
torii: {
remoteServiceName: 'iframe',
providers: { /* ... */ }
}
};
return ENV;
};
```
If you only want the iframe for a single provider you can include the
`remoteServiceName` value in the configuration for that provider.
```JavaScript
/* jshint node: …
```
> Iframe Service

- lib/torii/routing/authenticated-route-mixin.js
- test/tests/unit/routing/authenticated-route-mixin-test.js
Having the `transition` sent through the `accessDenied` action makes it much easier to redirect to the desired route after completing the normal signIn flow.
> Sending the `transition` as a parameter with the `accessDenied` action

- package.json
`grunt-contrib-testem` has been renamed to `grunt-testem-mincer` https://github.com/inossidabile/grunt-testem-mincer/commit/10cb9d1589a6b237fb62e370140a6bc98603af9b. The original package name is no longer available on npm which prevents a fresh `npm install` from working.
> grunt-contrib-testem has been renamed to grunt-testem-mincer

- README.md
- lib/torii/services/torii.js
Adds documentation explaining that `options` passed to `this.get('torii').open(providerName, options)` will be passed to the `open` method of  `<providerName>`.
fixes #88
> Document that `options` is passed through to the provider's methods

- README.md
- lib/torii/bootstrap/torii.js
- lib/torii/initializers/initialize-torii.js
- test/tests/unit/bootstrap/torii-test.js
Removes code that attempted to inject ember-data's store on
torii-providers and torii-adapters. Consumer code should instead use
`store: Ember.inject.service()` if their custom providers or adapters
need the store.
refs #270
refs #261
> [breaking] Remove eager injection of ember-data store

- addon/mixins/ui-service-mixin.js
- tests/unit/services/popup-test.js
Currently, Torii tracks in flight requests using a localStorage key. If the browser window is closed, that key remains behind. This results in Torii thinking there is an in flight request the next time it runs on that same domain. It then attempts to close the opened remote, which fails:
The solution implemented here uses the browser's `onbeforeunload` hook to remove the pending request key from localStorage, ensuring a clean state for the next page load.
1. Open a torii session that results in a popup or iframe opening.
2. Close the parent browser window without touching the remote (iframe/popup) window.
3. Navigate back to the page in a new window, and attempt to open another torii session.
> Cleanup pending requests

- index.js
Makes torii safer to use in a nested addon or in an in-repo-addon.
Different incantations of the `_super.included` hook (see below) in an in-repo-addon
change the context that torii's `included` gets called with.
See also https://github.com/ember-cli/ember-cli/issues/5747#issuecomment-206357164
and https://github.com/machty/ember-concurrency/pull/46
* `this._super.included(app)` vs `this._super.included.apply(this, arguments)`
in another addon will change whether `this.app` exists in torii's `included` hook
> Recursively find hostApp

- circle.yml
- config/ember-try.js
The ember-try config is actually broken currently which breaks the CircleCLI build…
This also updates the node version used on Circle to 4 from 0.10.
> fix Circle CI build

- addon/lib/query-string.js
- config/ember-try.js
- package.json
- tests/acceptance/ember-init-test.js
- tests/unit/lib/query-string-test.js
This PR is a rebase of #341, with a few additional changes to get tests passing:
* Upgrade ember-try to latest and allow beta and canary to fail (for now)
* Specify a dummy renderer for one unit test that does component instantiation
> Fix failing build

- addon/services/torii-session.js
- tests/unit/redirect-handler-test.js
- tests/unit/services/popup-test.js
rebased version of #322 (to fix unrelated failures due to node version). Thanks @locks, @drewchandler, @kybishop and @kturney who all opened PRs to fix the issue. ❤️
> Replace `Ember.K` usage with JavaScript syntax  (rebased)

- README.md
- bower.json
The last AMD build that was published to bower was v0.6.1.
> Remove mentions of bower installation in README

- addon/services/torii-session.js
This should fix issues folks are having with 2.13 and get the test suite passing again
Fixes https://github.com/Vestorly/torii/issues/353
Fixes https://github.com/Vestorly/torii/issues/349
> lookup torii service instead of using get

- addon/router-dsl-ext.js
- app/instance-initializers/setup-routes.js
https://emberjs.com/deprecations/v2.x/#toc_ember-router-router-renamed-to-ember-router-_routermicrolib
> Ember 2.13 - Fix deprecated usage of router.router

- addon/compat/get-router-instance.js
- addon/compat/get-router-lib.js
- addon/router-dsl-ext.js
- app/instance-initializers/setup-routes.js
This consolidates the compatibility fixes from #354 to `compat/` for
easier extraction in the future.
> Isolate compatibility code to `/compat`

- test-support/helpers/torii.js
This PR would make the torii session helper get the `sessionServiceName` that the user has defined.
Fixes the issue: [https://github.com/Vestorly/torii/issues/307](https://github.com/Vestorly/torii/issues/307)
> Genericize torii session name.

- app/services/torii-session.js
`app/services/torii-session` tried to require `torii/services/session` which does not exist.
This triggered a warning in my console output.
I assume it should be requiring `torii/services/torii-session`
> App torii session should require addon torii session

- addon/providers/oauth2-code.js
This is a regression introduced by commit f0b214f ("Deprecate Redirect
Handler, use public/redirect.html as redirect target", 2017-05-22).
Supersedes part of #370
cc @sukima
> Make redirectUri configurable again

- README.md
- addon/redirect-handler.js
- app/initializers/initialize-torii-callback.js
from @sukima's work on #370:
* Adds a way to disable the deprecated behavior. This caused a bug where attempting to refresh a Torii enabled app would cause the second instance to freeze because it notices the localStorage key and attempts to close the main window and then crashes. A second refresh will work because the localStorage key was removed before the crash. And a third refresh would be back in the same boat. The patterns continues on. Since we have a new redirect.html instead this behavior can be switched off via a configuration flag until the deprecated code is removed in a future release.
Adding `disableRedirectInitializer` to the torii config skips initializing the redirect handler altogether.
> add disableRedirectInitializer option

- public/redirect.html
While totally not necessary for this behavior to work, adding a DOCTYPE and a `<meta charset>` tag is somewhat of a best practice. Happy to split this into two commits if that makes this easier. :)
> Add DOCTYPE and character set declaration to redirect.html

- addon/providers/oauth2-code.js
- tests/unit/providers/oauth2-code-test.js
Some providers (ahem, salesforce) return authorization codes that need to be URI-decoded (salesforce ones tend to have a '==' at the end). Plus it's probably a good idea to `decodeURIComponent` strings that come from a URL anyway.
Closes #323
> URI-decode the OAuth2 authorization code

- index.js
I'm making addons that depend on torii. They handle configuring torii for you. It would be helpful to make this warning go away for that scenario.
> Don't warn on empty config when included by an addon

- config/ember-try.js
- package.json
- yarn.lock
The bug in ember-try was fixed, so we no longer need this explicit bower dependency to get ember-try to work in CI 💯
> remove last vestiges of bower

- addon/providers/facebook-oauth2.js
- tests/unit/providers/facebook-oauth2-test.js
The [Facebook API docs](https://developers.facebook.com/docs/apps/versions#versioning) recommend to always make versioned calls:
> An unversioned call will always point to the oldest version still available at the top of the chart. This is currently v2.1, but after two years it'll be v2.2, then v2.3, etc.
> 
> Because of this, our recommendation is to always specify versions when making calls, where possible.
This is currently not possible in torii. This PR adds an optional configuration parameter `apiVersion` that can be used to specify the version to be used. There is an additional check to make sure that the parameter is of the right shape as it has to be something like `v3.2`.
> Allow versioning of Facebook OAuth2 API
